#-------------------------------
# General Site Settings
title: Vincent Dorier
logo: # You can add own logo. For example '/images/logo.png'.
description: Site personnel de Vincent Dorier, auteur.
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://vincentdorier.com" # The base hostname & protocol for your site, e.g. http://example.com

future: true

#-------------------------------
# Author Settings
author:
  name: Vincent Dorier
  avatar: '/images/vincentdorier.jpeg'

#-------------------------------
# Footer section
# Example of adding a new link to the footer - {icon: "ion-logo-github", link: "https://github.com"}
# Other icons can be found at https://ionicons.com
social:
  facebook: https://facebook.com/Vincent.Dorier.Auteur
  instagram: https://instagram.com/vincent.dorier.auteur
#- {icon: "ion-logo-facebook", link: "https://facebook.com/Vincent.Dorier.Auteur"}
#- {icon: "ion-logo-instagram", link: "https://instagram.com/vincent.dorier.auteur"}
#- {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
#- {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
#- {icon: "ion-logo-github", link: "https://github.com"}
#- {icon: "ion-logo-twitter", link: "https://twitter.com"}


#-------------------------------
# Comment Section (Disqus)
# disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: false # To enable the mailchimp form, use the value true. To turn off use the value false.
mailchimp-identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 9
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
#  - scope:
#      path: '_romans'
#    values:
#      permalink: /romans/:title
#  - scope:
#      path: '_univers'
#    values:
#      permalink: /univers/:title
#  - scope:
#      path: '_evenements'
#    values:
#      permalink: /evenements/:title


collections:
  romans:
    output: true
    permalink: /romans/:title/
  univers:
    output: true
    permalink: /univers/:title/
  evenements:
    output: true
    permalink: /evenements/:year-:month-:day-:title/

include:
  - _pages
  - _romans
  - _univers
  - _evenements

exclude:
  - old/
  - vendor/bundle/
  - Gemfile
  - Gemfile.lock
  - README.md

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed
